### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by WilliamBlais** [Pytal/deploy-env#15]
Hi,

Thanks for your package.

Using node v12.18.2, I get this error; 

w@Williams-MacBook-Pro umsFront % deploy-env
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/local/lib/node_modules/deploy-env/lib/helpers/helpers.js
- /usr/local/lib/node_modules/deploy-env/lib/utils/vercel-env.js
- /usr/local/lib/node_modules/deploy-env/lib/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/deploy-env/lib/helpers/helpers.js:1:135)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/deploy-env/lib/helpers/helpers.js',
    '/usr/local/lib/node_modules/deploy-env/lib/utils/vercel-env.js',
    '/usr/local/lib/node_modules/deploy-env/lib/cli.js'
  ]
}

**Comment by Pytal** [comment]
Thanks reporting this!

Fix has been released in [`v1.1.3`](https://github.com/Pytal/deploy-env/releases/tag/v1.1.3)

**Comment by Pytal** [comment]
@WilliamBlais did you get `v1.1.3` working?

**Comment by WilliamBlais** [comment]
> @WilliamBlais did you get `v1.1.3` working?

I did, thank you!
