### ISSUE TITLE
Error while executing cmd

### ISSUE THREAD

**Issue by Guizzoni** [Pytal/deploy-env#24]
Hi, I'm having the following error while executing `deploy-env production`:

> (node:19829) UnhandledPromiseRejectionWarning: Error: Failed to find .rc file at default paths: [./.env-cmdrc,./.env-cmdrc.js,./.env-cmdrc.json]
    at getRCFile (/home/guizz/.nvm/versions/node/v14.4.0/lib/node_modules/deploy-env/node_modules/env-cmd/dist/get-env-vars.js:108:11)
    at async Object.exports.getEnvVarMap (/home/guizz/.nvm/versions/node/v14.4.0/lib/node_modules/deploy-env/lib/utils/get-env.js:1:386)
    at async Object.exports.deployEnv (/home/guizz/.nvm/versions/node/v14.4.0/lib/node_modules/deploy-env/lib/utils/vercel-env.js:1:622)

**Comment by Pytal** [comment]
What file are you using to store your environment variables?

**Comment by Guizzoni** [comment]
I'm using a `.env` file, it works as intended when running a dev build with env-cmd...

**Comment by Pytal** [comment]
Fix released in v1.1.5
